feat: add images for core components
sighupio/fury-distribution-container-image-sync pull request #145
Opened 2023-06-08 07:55 UTC by giusepperotella

Added images for the following components:
- **coredns**: v1.6.7, v1.7.0
- **kube-apiserver**: v1.18.14, v1.20.15
- **kube-controller-manager**: v1.18.14, v1.20.15
- **kube-proxy**: v1.18.14, v1.20.15
- **kube-scheduler**: v1.18.14, v1.20.15

2023-06-08 09:37 UTC, ralgozino requested changes

2023-06-08 09:37 UTC, ralgozino commented on modules/on-premises/images.yml
> +      - registry.sighup.io/fury/on-premises/coredns
To follow the other images nomenclature I believe this one should be:
```suggestion
      - registry.sighup.io/fury/on-premises/coredns/coredns
```

2023-06-08 13:48 UTC, ralgozino approved these changes
lgtm

2023-06-09 13:20 UTC, nutellinoit requested changes
We need also all the images till 1.25

2023-07-03 07:10 UTC, ralgozino approved these changes
lgtm

2023-07-18 09:12 UTC, merged