Refactor scan and patch steps in parallel and provide report after patching
sighupio/fury-distribution-container-image-sync pull request #243
Opened 2024-10-04 17:40 UTC by g-iannelli

2024-10-17 15:40 UTC, ralgozino requested changes

2024-10-17 15:40 UTC, ralgozino commented on CVEs/patch_images_with_copacetic.sh
> +      --arg image_patched "$image_to_patch-patched" \
```suggestion
      --arg image_patched "${image_to_patch}-patched" \
```

2024-10-17 15:40 UTC, ralgozino commented on CVEs/patch_images_with_copacetic.sh
> +    echo "FROM $image_to_patch-patched" | DOCKER_BUILDKIT=0 docker build \
```suggestion
    info "Tag ${image_to_patch}-patched as secured image: $secured_image"
    echo "FROM ${image_to_patch}-patched" | DOCKER_BUILDKIT=0 docker build \
```

2024-10-17 15:40 UTC, ralgozino commented on CVEs/patch_images_with_copacetic.sh
> +    sed -i'.unsecured' s#"$image_to_patch-patched"#"$secured_image"# "$PATCH_REPORT_OUTPUT_FILE"
```suggestion
    sed -i'.unsecured' s#"${image_to_patch}-patched"#"$secured_image"# "$PATCH_REPORT_OUTPUT_FILE"
```

2024-10-17 15:40 UTC, ralgozino commented on CVEs/patch_images_with_copacetic.sh
> +    docker rmi -f "$image_to_patch-patched"
```suggestion
    info "Cleanup ${image_to_patch}-patched"
    buildctl --addr tcp://127.0.0.1:8888 prune
    docker rmi -f "${image_to_patch}-patched"
```

2024-10-17 15:40 UTC, ralgozino commented on CVEs/scan_vuln.sh
> +    echo "$image | ERROR PROCESSING! " >> "${SCAN_ERROR_OUTPUT_FILE}"
should we log also here to stdout with error or warning?

2024-10-17 15:42 UTC, ralgozino requested changes
The How to got outdated with the latest changes, it needs to be worked on a little.

I left some very small suggestions in the code, nothing critical, only stye.

2024-10-18 07:52 UTC, g-iannelli commented on CVEs/patch_images_with_copacetic.sh
> +echo -n "" > "${PATCH_ERROR_OUTPUT_FILE}"
On MacOs touch will not clean the file content.

```
$ echo -n "" > example_file
$ echo "hello world" >> example_file

$ cat example_file
hello world

$ touch example_file

$ cat example_file
hello world
```

2024-10-18 09:41 UTC, ralgozino commented on CVEs/patch_images_with_copacetic.sh
> +echo -n "" > "${PATCH_ERROR_OUTPUT_FILE}"
you are absolutely right

2024-10-18 10:38 UTC, g-iannelli commented on CVEs/Makefile
> +			`find $(KFD_VERSION)/.furyctl/bin -name kustomize -type f` build `dirname $$kustomize` >> $(KFD_VERSION)/built.yaml; \
The awk search is quite fast. It is performed in about 4 seconds. Maybe it will not improve the speed of the task.

2024-10-18 12:32 UTC, ralgozino approved these changes
code-wise LGTM.

2024-10-18 12:43 UTC, ralgozino approved these changes

2024-10-21 13:04 UTC, merged